2018-10-23 08:39:46,540 ERROR 15008 nodejs.ClusterClientNoResponseError: client no response in 25871897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\evey0\Desktop\th\node_modules\_cluster-client@2.1.1@cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: "ClusterClientNoResponseError"
pid: 15008
hostname: DESKTOP-ASUCCPF

2018-10-23 12:06:38,955 ERROR 8456 [-/undefined/-/39ms GET /public/banner.png] nodejs.EBADFError: EBADF: bad file descriptor, read
EBADFError: EBADF: bad file descriptor, read
errno: -4083
code: "EBADF"
syscall: "read"
headerSent: true
name: "EBADFError"
pid: 8456
hostname: DESKTOP-ASUCCPF

2018-10-23 12:56:01,838 ERROR 15760 nodejs.ClusterClientNoResponseError: client no response in 431269ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\evey0\Desktop\th\node_modules\_cluster-client@2.1.1@cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: "ClusterClientNoResponseError"
pid: 15760
hostname: DESKTOP-ASUCCPF

2018-10-23 18:05:46,688 ERROR 6796 nodejs.ClusterClientNoResponseError: client no response in 10735729ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\evey0\Desktop\th\node_modules\_cluster-client@2.1.1@cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: "ClusterClientNoResponseError"
pid: 6796
hostname: DESKTOP-ASUCCPF

2018-10-23 20:31:06,730 ERROR 6796 nodejs.ClusterClientNoResponseError: client no response in 5679854ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\evey0\Desktop\th\node_modules\_cluster-client@2.1.1@cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: "ClusterClientNoResponseError"
pid: 6796
hostname: DESKTOP-ASUCCPF

2018-10-23 21:20:32,753 ERROR 6796 nodejs.ClusterClientNoResponseError: client no response in 1125912ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\evey0\Desktop\th\node_modules\_cluster-client@2.1.1@cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: "ClusterClientNoResponseError"
pid: 6796
hostname: DESKTOP-ASUCCPF

2018-10-24 00:51:01,092 ERROR 6796 nodejs.ClusterClientNoResponseError: client no response in 10808191ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\evey0\Desktop\th\node_modules\_cluster-client@2.1.1@cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: "ClusterClientNoResponseError"
pid: 6796
hostname: DESKTOP-ASUCCPF

